"""Shared test fixtures for Gemia primitives."""
from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pytest


@pytest.fixture
def sample_image() -> np.ndarray:
    """64x64 BGR gradient image, float32 [0, 1]."""
    h, w = 64, 64
    r = np.linspace(0, 1, w, dtype=np.float32).reshape(1, w, 1).repeat(h, axis=0)
    g = np.linspace(0, 1, h, dtype=np.float32).reshape(h, 1, 1).repeat(w, axis=1)
    b = np.full((h, w, 1), 0.3, dtype=np.float32)
    return np.concatenate([b, g, r], axis=2)  # BGR


@pytest.fixture
def sample_image_uint8(sample_image: np.ndarray) -> np.ndarray:
    """Same gradient as sample_image but uint8 [0, 255]."""
    return (sample_image * 255).astype(np.uint8)


@pytest.fixture
def sample_gray() -> np.ndarray:
    """64x64 single-channel gradient, float32 [0, 1]."""
    return np.linspace(0, 1, 64 * 64, dtype=np.float32).reshape(64, 64)


@pytest.fixture
def sample_audio() -> np.ndarray:
    """1-second 440 Hz sine wave, float32 [-1, 1], 22050 Hz sample rate."""
    sr = 22050
    t = np.linspace(0, 1, sr, endpoint=False, dtype=np.float32)
    return np.sin(2 * np.pi * 440 * t)


@pytest.fixture
def sample_video_path(tmp_path: Path) -> str:
    """2-second test video generated by ffmpeg testsrc2."""
    out = tmp_path / "test_input.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-f", "lavfi",
            "-i", "testsrc2=duration=2:size=128x128:rate=15",
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
            str(out),
        ],
        capture_output=True,
        check=True,
    )
    return str(out)
