"""Shared test fixtures for Gemia primitives."""
from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pytest


@pytest.fixture(autouse=True)
def _sandbox_gemia_memory_for_agent_tests(request, tmp_path, monkeypatch):
    """Keep the agent loop's auto daily-log out of the user's real ~/.gemia.

    The v3 agent writes a one-line entry to ``gemia.memory.append_daily_entry``
    when a turn completes. Older agent-loop integration tests don't sandbox the
    memory root, so without this they'd silently pollute the real
    ``~/.gemia/memory/daily``. Redirect HOME to a tmp dir for those tests only
    (same mechanism test_memory.py uses; memory_root() reads Path.home()), so
    the real store is never touched. Scoped by node id so the rest of the suite
    keeps its normal HOME.
    """
    nid = request.node.nodeid
    if any(t in nid for t in ("test_v3_", "agent_loop", "test_automation_loop")):
        home = tmp_path / "home"
        (home / ".gemia" / "memory").mkdir(parents=True, exist_ok=True)
        monkeypatch.setenv("HOME", str(home))
    yield


@pytest.fixture
def sample_image() -> np.ndarray:
    """64x64 BGR gradient image, float32 [0, 1]."""
    h, w = 64, 64
    r = np.linspace(0, 1, w, dtype=np.float32).reshape(1, w, 1).repeat(h, axis=0)
    g = np.linspace(0, 1, h, dtype=np.float32).reshape(h, 1, 1).repeat(w, axis=1)
    b = np.full((h, w, 1), 0.3, dtype=np.float32)
    return np.concatenate([b, g, r], axis=2)  # BGR


@pytest.fixture
def sample_image_uint8(sample_image: np.ndarray) -> np.ndarray:
    """Same gradient as sample_image but uint8 [0, 255]."""
    return (sample_image * 255).astype(np.uint8)


@pytest.fixture
def sample_gray() -> np.ndarray:
    """64x64 single-channel gradient, float32 [0, 1]."""
    return np.linspace(0, 1, 64 * 64, dtype=np.float32).reshape(64, 64)


@pytest.fixture
def sample_audio() -> np.ndarray:
    """1-second 440 Hz sine wave, float32 [-1, 1], 22050 Hz sample rate."""
    sr = 22050
    t = np.linspace(0, 1, sr, endpoint=False, dtype=np.float32)
    return np.sin(2 * np.pi * 440 * t)


@pytest.fixture
def sample_video_path(tmp_path: Path) -> str:
    """2-second test video generated by ffmpeg testsrc2."""
    out = tmp_path / "test_input.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-f", "lavfi",
            "-i", "testsrc2=duration=2:size=128x128:rate=15",
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
            str(out),
        ],
        capture_output=True,
        check=True,
    )
    return str(out)


@pytest.fixture(autouse=True)
def isolated_skill_telemetry(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setenv("GEMIA_SKILL_TELEMETRY_DB", str(tmp_path / "skill_telemetry.sqlite3"))


@pytest.fixture(autouse=True)
def _force_cpu_video_encoder(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin video encoding to libx264/libx265 across the suite.

    Production auto-detects GPU encoders (VideoToolbox / NVENC / QSV), which
    would make ffmpeg output host-dependent — VideoToolbox on the dev's Mac,
    libx264 on CI. Forcing CPU keeps every integration test deterministic and
    byte-identical to the pre-GPU baseline. Tests that exercise the detection /
    GPU-fallback paths opt back in by setting ``GEMIA_VIDEO_ENCODER=auto`` and
    monkeypatching ``detect_supported_encoders`` themselves.
    """
    monkeypatch.setenv("GEMIA_VIDEO_ENCODER", "cpu")
