"""gemia.audio — Audio primitive operations.

All functions work with float32 ndarrays [-1, 1].
"""
from gemia.audio.basics import load, save, trim, concat, mix
from gemia.audio.dynamics import normalize, compress, adjust_gain, lufs_normalize
from gemia.audio.frequency import eq, highpass, lowpass
from gemia.audio.time_pitch import time_stretch, pitch_shift, detect_bpm
from gemia.audio.analysis import silence_detect, beat_detect, music_extend, stem_separate, loudness_meter, audio_visualizer
from gemia.audio.effects import (
    voice_convert, auto_mix, ducker, voice_isolate, pitch_correction,
    dynamic_eq_match, level_matcher, spectral_denoise,
    remove_silence, speaker_separate, create_adr_cues,
    noise_gate, audio_compressor, stereo_widener, audio_reverb, audio_fade,
    audio_trim_silence, text_to_speech,
    audio_normalize_loudness, audio_pitch_shift_semitones,
    audio_mix_to_mono, audio_concat, audio_ducking, audio_speed,
    audio_volume, audio_equalizer, audio_reverse,
    audio_fade_in, audio_fade_out,
    audio_trim, audio_mix_stereo,
    audio_sample_rate_convert, audio_channels_to_mono,
    audio_loudness_normalize, audio_bit_depth_convert,
    audio_stereo_to_lr,
    audio_echo, audio_chorus,
    audio_tremolo, audio_flanger,
    audio_vibrato, audio_robot,
    audio_pitch_up,
    audio_normalize_peak, audio_stereo_enhance,
    audio_bass_boost, audio_treble_boost,
    audio_telephone, audio_lowpass,
    audio_highpass, audio_compand,
    audio_mix_tracks, audio_silence_insert,
    audio_vinyl, audio_normalize_rms,
    audio_silence_detect, audio_export_wav,
    audio_crossfade, audio_ducking_auto,
    audio_format_convert, audio_waveform_image,
    audio_noise_reduce,
    audio_speed_change,
    audio_stereo_swap,
    audio_generate_tone,
    audio_silence_trim,
    audio_resample,
    audio_normalize_to_target_db,
    audio_apply_eq_bands,
    audio_gate,
    audio_pitch_detect,
    audio_measure_rms,
    audio_duration,
    audio_mix_with_volume,
    audio_fade_both,
    audio_split_at,
    audio_loop,
    audio_info,
    audio_merge_channels,
    audio_trim_to_duration,
    audio_peak_detect,
    audio_loudness_scan,
    audio_trim_to_beats,
    audio_stereo_panning,
    audio_cut_silence,
    audio_pitch_formant_shift,
    audio_vinyl_crackle,
    audio_haas_effect,
    audio_spectral_gate,
    audio_pitch_wobble,
    audio_room_tone,
    audio_side_chain_compress,
    audio_beat_sync_cut,
    audio_binaural_beat,
    audio_stutter,
    audio_auto_duck,
    audio_pitch_harmonize,
    audio_tremolo_lfo,
    audio_vinyl_warmth,
    audio_telephone_filter,
    audio_radio_effect,
    audio_crowd_ambience,
    audio_pitch_octave_down,
    audio_granular_freeze,
    audio_reverb_room,
    audio_distortion,
    audio_chorus_stereo,
    audio_wah_effect,
    audio_pitch_vibrato,
    audio_tape_saturation,
    audio_vinyl_pop,
    audio_flanger_jet,
    audio_binaural_pan,
    audio_sidechain_pump,
    audio_stereo_imager,
    audio_spatial_reverb,
    audio_pitch_glide,
    audio_granular_pitch,
    audio_vinyl_hiss,
)

__all__ = [
    "load", "save", "trim", "concat", "mix",
    "normalize", "compress", "adjust_gain",
    "eq", "highpass", "lowpass",
    "time_stretch", "pitch_shift", "detect_bpm",
    "silence_detect",
    "beat_detect", "music_extend", "stem_separate", "loudness_meter", "audio_visualizer",
    "voice_convert", "auto_mix", "ducker",
    "lufs_normalize",
    "voice_isolate",
    "pitch_correction",
    "dynamic_eq_match",
    "level_matcher",
    "spectral_denoise",
    "remove_silence", "speaker_separate", "create_adr_cues",
    "noise_gate", "audio_compressor", "stereo_widener", "audio_reverb", "audio_fade",
    "audio_trim_silence", "text_to_speech",
    "audio_normalize_loudness", "audio_pitch_shift_semitones",
    "audio_mix_to_mono", "audio_concat", "audio_ducking", "audio_speed",
    "audio_volume", "audio_equalizer", "audio_reverse",
    "audio_fade_in", "audio_fade_out",
    "audio_trim", "audio_mix_stereo",
    "audio_sample_rate_convert", "audio_channels_to_mono",
    "audio_loudness_normalize", "audio_bit_depth_convert",
    "audio_stereo_to_lr",
    "audio_echo", "audio_chorus",
    "audio_tremolo", "audio_flanger",
    "audio_vibrato", "audio_robot",
    "audio_pitch_up",
    "audio_normalize_peak", "audio_stereo_enhance",
    "audio_bass_boost", "audio_treble_boost",
    "audio_telephone", "audio_lowpass",
    "audio_highpass", "audio_compand",
    "audio_mix_tracks", "audio_silence_insert",
    "audio_vinyl", "audio_normalize_rms",
    "audio_silence_detect", "audio_export_wav",
    "audio_crossfade", "audio_ducking_auto",
    "audio_format_convert", "audio_waveform_image",
    "audio_noise_reduce",
    "audio_speed_change",
    "audio_stereo_swap",
    "audio_generate_tone",
    "audio_silence_trim",
    "audio_resample",
    "audio_normalize_to_target_db",
    "audio_apply_eq_bands",
    "audio_gate",
    "audio_pitch_detect",
    "audio_measure_rms",
    "audio_duration",
    "audio_mix_with_volume",
    "audio_fade_both",
    "audio_split_at",
    "audio_loop",
    "audio_info",
    "audio_merge_channels",
    "audio_trim_to_duration",
    "audio_peak_detect",
    "audio_loudness_scan",
    "audio_trim_to_beats",
    "audio_stereo_panning",
    "audio_cut_silence",
    "audio_pitch_formant_shift",
    "audio_vinyl_crackle",
    "audio_haas_effect",
    "audio_spectral_gate",
    "audio_pitch_wobble",
    "audio_room_tone",
    "audio_side_chain_compress",
    "audio_beat_sync_cut",
    "audio_binaural_beat",
    "audio_stutter",
    "audio_auto_duck",
    "audio_pitch_harmonize",
    "audio_tremolo_lfo",
    "audio_vinyl_warmth",
    "audio_telephone_filter",
    "audio_radio_effect",
    "audio_crowd_ambience",
    "audio_pitch_octave_down",
    "audio_granular_freeze",
    "audio_reverb_room",
    "audio_distortion",
    "audio_chorus_stereo",
    "audio_wah_effect",
    "audio_pitch_vibrato",
    "audio_tape_saturation",
    "audio_vinyl_pop",
    "audio_flanger_jet",
    "audio_binaural_pan",
    "audio_sidechain_pump",
    "audio_stereo_imager",
    "audio_spatial_reverb",
    "audio_pitch_glide",
    "audio_granular_pitch",
    "audio_vinyl_hiss",
]
