"Resolve 21 social-media upload preset manifests."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from gemia.video.timeline_assets import probe_media


DEFAULT_UPLOAD_PLATFORMS: list[dict[str, Any]] = [
    {"id": "youtube_shorts", "label": "YouTube Shorts", "max_width": 1080, "max_height": 1920, "max_bitrate_mbps": 12, "container": "mp4"},
    {"id": "tiktok", "label": "TikTok", "max_width": 1080, "max_height": 1920, "max_bitrate_mbps": 10, "container": "mp4"},
    {"id": "instagram_reels", "label": "Instagram Reels", "max_width": 1080, "max_height": 1920, "max_bitrate_mbps": 8, "container": "mp4"},
    {"id": "x_video", "label": "X Video", "max_width": 1920, "max_height": 1080, "max_bitrate_mbps": 15, "container": "mp4"},
]


def render_social_media_upload_preset_manifest(
    input_paths: list[str],
    output_dir: str,
    *,
    package_id: str = "resolve21_social_media_upload_preset",
    platforms: list[dict[str, Any]] | None = None,
    privacy: str = "draft",
    compression_profile: str = "balanced",
    include_captions: bool = True,
) -> str:
    """Emit safe platform upload-preset metadata without storing credentials."""
    if not input_paths:
        raise ValueError("input_paths must contain at least one media path")
    output_root = Path(output_dir).expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    package = _safe_id(package_id)
    privacy_mode = _safe_choice(str(privacy or "draft"), {"draft", "private", "unlisted", "public"})
    profile = _safe_choice(str(compression_profile or "balanced"), {"fast", "balanced", "quality"})
    targets = [_normalize_platform(raw, index) for index, raw in enumerate(platforms or DEFAULT_UPLOAD_PLATFORMS)]

    assets = []
    for index, raw_path in enumerate(input_paths):
        source = Path(raw_path).expanduser().resolve()
        if not source.exists():
            raise FileNotFoundError(f"Input media not found: {source}")
        if not source.is_file():
            raise OSError(f"Input media is not a file: {source}")
        probe = probe_media(str(source))
        if str(probe.get("media_kind") or "video") == "audio":
            raise ValueError(f"Social upload presets require video or image media: {source}")
        assets.append(
            {
                "asset_id": f"upload_asset_{index:02d}_{_safe_id(source.stem)}",
                "source_path": str(source),
                "asset_ref": _asset_ref(source, probe),
                "source_probe": probe,
                "upload_readiness": _readiness(probe),
            }
        )

    upload_jobs = []
    for platform in targets:
        for asset in assets:
            upload_jobs.append(
                {
                    "job_id": f"{package}_{asset['asset_id']}_{platform['platform_id']}",
                    "asset_ref": asset["asset_ref"],
                    "platform": platform,
                    "delivery_file": _delivery_name(asset["source_path"], platform),
                    "compression": _compression(asset["source_probe"], platform, profile),
                    "metadata_template": {
                        "title": _title_from_path(asset["source_path"]),
                        "description": "Generated by Lumeri social upload preset manifest.",
                        "privacy": privacy_mode,
                        "captions": "sidecar_srt_or_embedded" if include_captions else "none",
                        "tags": ["lumeri", platform["platform_id"], profile],
                    },
                    "credential_policy": {
                        "stores_credentials": False,
                        "requires_connected_account_at_publish_time": True,
                        "secret_fields": [],
                    },
                    "validation": {
                        "ready_for_manual_upload": asset["upload_readiness"]["has_pixels"] and platform["max_width"] > 0,
                        "no_credentials_serialized": True,
                    },
                }
            )

    manifest = {
        "schema_version": 1,
        "effect": "resolve21_social_media_upload_preset_manifest",
        "rendered_at": datetime.now(timezone.utc).isoformat(),
        "package": {
            "package_id": package,
            "asset_count": len(assets),
            "platform_count": len(targets),
            "job_count": len(upload_jobs),
            "privacy": privacy_mode,
            "compression_profile": profile,
        },
        "assets": assets,
        "upload_platforms": targets,
        "upload_jobs": upload_jobs,
        "resolve_controls": {
            "page": "Deliver",
            "preset_scope": "platform_upload_metadata_only",
            "direct_upload": "manual_or_connected_account_required",
        },
        "review_hints": [
            "manifest intentionally stores no credentials, cookies, passwords, or account ids",
            "jobs describe export/upload settings only; publishing is a later explicit action",
            "compression values are bounded by platform presets and source metadata",
        ],
    }
    manifest_path = output_root / "social_media_upload_preset_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return str(manifest_path)


def _normalize_platform(raw: dict[str, Any], index: int) -> dict[str, Any]:
    return {
        "platform_id": _safe_id(str(raw.get("id") or raw.get("platform") or f"platform_{index}")),
        "label": str(raw.get("label") or raw.get("name") or f"Platform {index + 1}"),
        "max_width": max(240, min(_optional_int(raw.get("max_width")) or 1080, 4320)),
        "max_height": max(240, min(_optional_int(raw.get("max_height")) or 1920, 4320)),
        "max_bitrate_mbps": max(1, min(_optional_int(raw.get("max_bitrate_mbps")) or 10, 80)),
        "container": _safe_choice(str(raw.get("container") or "mp4"), {"mp4", "mov"}),
    }


def _compression(probe: dict[str, Any], platform: dict[str, Any], profile: str) -> dict[str, Any]:
    source_w = int(probe.get("width") or platform["max_width"])
    source_h = int(probe.get("height") or platform["max_height"])
    scale = min(platform["max_width"] / max(source_w, 1), platform["max_height"] / max(source_h, 1), 1.0)
    width = max(2, int(round(source_w * scale)) // 2 * 2)
    height = max(2, int(round(source_h * scale)) // 2 * 2)
    multiplier = {"fast": 0.65, "balanced": 0.82, "quality": 1.0}[profile]
    bitrate = max(1.0, round(float(platform["max_bitrate_mbps"]) * multiplier, 2))
    return {
        "container": platform["container"],
        "video_codec": "h264",
        "audio_codec": "aac" if probe.get("has_audio") else "none",
        "resolution": f"{width}x{height}",
        "target_bitrate_mbps": bitrate,
        "frame_rate_policy": "preserve_source",
        "moov_atom": "fast_start",
    }


def _readiness(probe: dict[str, Any]) -> dict[str, Any]:
    return {
        "has_pixels": int(probe.get("width") or 0) > 0 and int(probe.get("height") or 0) > 0,
        "has_audio": bool(probe.get("has_audio")),
        "duration_seconds": round(float(probe.get("duration") or 0.0), 3),
    }


def _asset_ref(path: Path, probe: dict[str, Any]) -> str:
    duration = round(float(probe.get("duration") or 0.0), 3)
    return f"{_safe_id(path.stem)}:{path.stat().st_size}:{duration}:{int(probe.get('width') or 0)}x{int(probe.get('height') or 0)}"


def _delivery_name(source_path: str, platform: dict[str, Any]) -> str:
    stem = _safe_id(Path(source_path).stem)
    return f"{stem}_{platform['platform_id']}.{platform['container']}"


def _title_from_path(source_path: str) -> str:
    return re.sub(r"[_-]+", " ", Path(source_path).stem).strip().title() or "Lumeri Export"


def _optional_int(value: Any) -> int | None:
    try:
        return int(value) if value is not None else None
    except Exception:
        return None


def _safe_choice(value: str, choices: set[str]) -> str:
    key = _safe_id(value)
    if key in choices:
        return key
    return "mp4" if "mp4" in choices else sorted(choices)[0]


def _safe_id(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]+", "_", value.strip()).strip("_").lower() or "item"


__all__ = ["DEFAULT_UPLOAD_PLATFORMS", "render_social_media_upload_preset_manifest"]
